<?php
get_header();
?>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Article",
        "name": "Mau travelling? Kamu yang berhijab coba 12 gaya berpakaian ini bikin OOTD mu makin kece",
        "author": {
            "@type": "Person",
            "name": "Anisa f Haqqi"
        },
        "datePublished": "2018-01-04",
        "image": "https://i1.wp.com/www.indonesiatraveller.id/wp-content/uploads/hijab-4.jpg?fit=242%2C300&ssl=1",
        "articleBody": "Wah sudah mau tahun baru 2020, sudah <A href=\"https://www.indonesiatraveller.id/kalender-libur-nasional-2018/\">cek kalender terbaru</A> kaan. Kabar baik untuk kamu yang akan mengagendakan liburan pada tahun ini ternyata banyak libur panjangnya. Yeay! buat kamu para traveller yang berhijab ada tips keren nih Inspirasi fashion hijab traveller 2020. Biar dokumentasi travelling kamu makin kece."
    }
</script>
<?php
                        // $detect = new Mobile_Detect;
                        // // Any mobile device (phones or tablets).
                        // if ( $detect->isMobile() ) {
                        //         echo 'ismobile';
                        // }

                        // // Any tablet device.
                        // if( $detect->isTablet() ){
                        //         echo 'istablet';
                        // }

                        // // Exclude tablets.
                        // if( $detect->isMobile() && !$detect->isTablet() ){

                        // }

                        // // Check for a specific platform with the help of the magic methods:
                        // if( $detect->isiOS() ){

                        // }

                        // if( $detect->isAndroidOS() ){

                        // }
                        ?>
<main id="primary" class="site-main">

    <div class="page-hero">
        <div class="page-hero_image">
            <!-- <img src="https://via.placeholder.com/1600x600/f8f8f8/dddddd/"> -->
        </div>
        <div class="page-hero_content -light d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-xl-4 col-12">
                        <div class="hero-thumb">
                            <img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/">
                        </div>
                    </div>
                    <div class="col-lg-7 col-xl-7 col-12">
                        <span class="hero-label"><a href="#">Travel news</a></span>
                        <h1 class="hero-title mb-3">Kyoto and Nara 2 or 3-Day Bullet Train Tour from Tokyo</h1>
                        <div class="hero-description">
                            <p>Ex modi praesentium veritatis perferendis, voluptatem quod quos Ex modi praesentium
                                veritatis perferendis, voluptatem quod quos nulla corrupti nihil et architecto expedita.
                                nulla corrupti nihil et architecto expedita.</p>
                        </div>
                        <button type="button" class="btn btn-outline-light mt-3">Read more</button>
                    </div>
                </div>
                <div class="row mb-3 mt-3">
                    <div class="col-12">
                        <span class="hero-label"><a href="#">Featured posts</a></span>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-lg-4  d-flex align-items-stretch">
                        <div class="post-item -hero shadow-sm">
                            <div class="post-item_text">
                                <span class="meta-category"><a href="#">Travel news</a></span>
                                <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4  d-flex align-items-stretch">
                        <div class="post-item -hero shadow-sm">
                            <div class="post-item_text">
                                <span class="meta-category"><a href="#">Travel news</a></span>
                                <h1><a href="#">This incredible oceanfront geothermal lagoon has opened in Iceland</a>
                                </h1>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4  d-flex align-items-stretch">
                        <div class="post-item -hero shadow-sm">
                            <div class="post-item_text">
                                <span class="meta-category"><a href="#">Travel news</a></span>
                                <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row section-row">
            <div class="col-lg-6 col-xl-6 col-8">
                <div class="section-title text-left">Trending</div>
            </div>
            <div class="col-lg-6 col-xl-6 col-4   d-flex justify-content-end align-items-center">
                <div class="section-more text-right"><a href=""><span>Browse all</span> <i
                            class="bi bi-arrow-right-square-fill"></i></a></div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-xl-6 d-flex align-items-stretch">
                <div class="post-item -first">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/800x400/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text -featured">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                        <div class="post-item_excerpt">
                            Ex modi praesentium veritatis perferendis, voluptatem quod quos nulla corrupti nihil et
                            architecto expedita.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-6 d-flex align-items-stretch">
                <div class="post-item">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/800x400/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text -featured">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                        <div class="post-item_excerpt">
                            Ex modi praesentium veritatis perferendis, voluptatem quod quos nulla corrupti nihil et
                            architecto expedita.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-6">
                <div class="row section-row">
                    <div class="col-lg-6 col-xl-6 col-8">
                        <div class="section-title text-left">Destinations</div>
                    </div>
                    <div class="col-lg-6 col-xl-6 col-4 d-flex justify-content-end align-items-center">
                        <div class="section-more text-right"><a href=""><span>Browse all</span> <i
                                    class="bi bi-arrow-right-square-fill"></i></a></div>
                    </div>
                </div>
                <div class="post-item -list -right">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">What to see at these new museum openings around the US</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
                <div class="post-item -list -right">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">This incredible oceanfront geothermal lagoon has opened in Iceland</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
                <div class="post-item -list -right">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Greece opens beaches as international visitors return</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
                <div class="post-item -list -right">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Easygoing Graz is perfect for a heart-stealing Austrian deep dive</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-6">
                <div class="row section-row">
                    <div class="col-lg-6 col-xl-6 col-8">
                        <div class="section-title text-left">Attractions</div>
                    </div>
                    <div class="col-lg-6 col-xl-6 col-4 d-flex justify-content-end align-items-center">
                        <div class="section-more text-right"><a href=""><span>Browse all</span> <i
                                    class="bi bi-arrow-right-square-fill"></i></a></div>
                    </div>
                </div>
                <div class="post-item -list -right ">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Hit the Appalachian Trail as it welcomes back long-distance trekkers</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
                <div class="post-item -list -right ">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">This incredible oceanfront geothermal lagoon has opened in Iceland</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">hon doe</span>
                    </div>
                </div>
                <div class="post-item -list -right ">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">US tourists in New York City can get a one-shot vaccine</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
                <div class="post-item -list -right ">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Greece opens beaches as international visitors return</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="page-hero">
        <div class="page-hero_image">
            <!-- <img src="https://via.placeholder.com/1600x600/f8f8f8/dddddd/"> -->
        </div>
        <div class="page-hero_content -light d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-xl-5 col-12 ">
                        <div class="hero-single-thumb mb-4 mb-lg-0 mb-xl-0">
                            <img src="https://via.placeholder.com/800x600/f8f8f8/dddddd/">
                        </div>
                    </div>
                    <div class="col-lg-7 col-xl-7 col-12  d-flex align-items-center order-xl-first order-lg-first">
                        <div class="hero-single-content">
                            <span class="hero-label"><a href="#">Travel news</a></span>
                            <h1 class="hero-title mb-3">Kyoto and Nara 2 or 3-Day Bullet Train Tour from Tokyo</h1>

                            <div class="hero-author">
                                <div class="hero-author_thumb">
                                    <img src="https://via.placeholder.com/65x65/f8f8f8/dddddd/">
                                </div>
                                <div class="hero-author_text">
                                    <h3>Jhon Doe</h3>
                                    <span>Fulltime Traveller</span>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-2 col-xl-2">
            </div>
            <div class="col-12 col-lg-6 col-xl-7">

                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non convallis nunc. Fusce scelerisque lacinia leo ut semper. Aliquam eget massa non purus venenatis ultricies ut cursus lorem. Aliquam egestas sed lorem eu bibendum. Nulla ac maximus lectus. In sed egestas ligula. Etiam consequat erat erat, eget pulvinar magna accumsan et. Nullam pretium accumsan odio non vulputate. Vestibulum faucibus ipsum turpis, et tincidunt libero faucibus eu. Vivamus lobortis libero a lorem dignissim, eget interdum ex tempor. Pellentesque a consectetur tortor. Sed porta eleifend magna quis mollis. Aenean tincidunt, nisl ac aliquam pharetra, lectus enim pulvinar est, auctor lacinia nulla ipsum vitae velit.
                    </p>
                    <p>
                    Donec facilisis nisi id ex facilisis, faucibus sodales mauris molestie. Nam maximus eu orci sed mattis. Nullam at dolor vitae nulla vestibulum hendrerit. In luctus dictum dolor, sit amet accumsan ipsum vestibulum sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus euismod mi sit amet viverra mollis. Aenean rhoncus tortor sed egestas sagittis. Curabitur pharetra scelerisque vehicula. Phasellus molestie magna ut est laoreet accumsan.
                    </p>
                    <p>
                    Pellentesque elementum lacus quis ante tincidunt, ut lacinia tellus rutrum. In id felis venenatis, varius orci eget, rutrum ex. Suspendisse auctor sem id arcu consectetur, vel luctus tellus porta. Phasellus tempor commodo ex, sed egestas tortor consequat nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In fermentum est at nunc cursus aliquam. Sed congue placerat magna, eu dapibus magna ullamcorper sit amet. Donec consequat rhoncus ex. Nulla nec tristique urna. Donec et elit diam. Integer sed libero sapien.
                    </p>
                    <p>
                    Quisque egestas varius odio, in consequat sem mattis eget. Aliquam ut sollicitudin eros, sed mollis diam. Duis ultrices risus et eros consectetur, eu pharetra turpis aliquet. Etiam congue leo lorem. Fusce et auctor ligula. Curabitur pellentesque a nisi laoreet fermentum. Integer in neque molestie, ultrices elit quis, faucibus nisl. Donec ullamcorper nulla ac nisi pretium, sit amet pretium velit malesuada. Ut feugiat venenatis neque eget faucibus.
                    </p>
                    <p>
                    Vestibulum varius quam imperdiet velit suscipit tristique. Suspendisse ut vulputate odio, non consectetur tortor. Integer commodo justo non leo aliquet, quis ultricies lorem viverra. Nulla dapibus neque vitae justo euismod lobortis. Etiam nec mi sed nunc semper dictum. Nullam pellentesque lectus vel arcu volutpat, in fermentum magna vulputate. Donec scelerisque diam id urna dignissim feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi volutpat erat vel magna dapibus tempor. Maecenas vitae risus auctor, convallis lorem eu, imperdiet mi. Nulla molestie a turpis et aliquet. Vestibulum fringilla pellentesque nunc. Duis laoreet semper odio quis pharetra. Fusce non felis interdum, efficitur nunc in, pulvinar ligula.
                    </p>
                    <p>
                    Phasellus venenatis congue massa a interdum. Integer tempus ipsum felis, porta varius nisi dignissim non. Mauris vulputate volutpat magna, ut mollis lacus imperdiet id. Aliquam scelerisque eros nunc, ac maximus sem malesuada non. Maecenas in massa massa. Praesent malesuada, nulla et dictum ullamcorper, est erat condimentum ex, gravida feugiat turpis libero vitae leo. Proin libero lorem, tincidunt et lobortis pharetra, gravida vitae odio. Duis ante nunc, dictum sed augue ac, sagittis placerat arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean tincidunt arcu quis arcu tristique tempus. Sed venenatis eu arcu sed pretium. Morbi diam tellus, auctor id interdum vitae, fringilla sed lorem.
                    </p>
                    <p>
                    Suspendisse venenatis pellentesque diam, vel pellentesque nunc facilisis vitae. In vitae quam sem. Pellentesque sodales tristique scelerisque. Donec dictum nunc interdum est molestie, vel mollis metus eleifend. Aliquam vitae magna mattis, faucibus nisl ac, efficitur massa. Vivamus sit amet urna ut purus tempus pretium. Fusce eget accumsan diam. Nullam pretium fringilla ligula vel tempus. Aenean orci elit, varius a accumsan eu, gravida eget elit. Quisque porttitor ultrices lectus vitae luctus. In hac habitasse platea dictumst. Mauris ullamcorper maximus ipsum, vel aliquam lacus laoreet in. Fusce vitae nibh id urna vehicula malesuada sed eget dui.
                    </p>
                    <p>
                    Nullam eu enim quis nibh placerat pretium. Duis feugiat varius dui. Aenean tincidunt egestas risus vitae facilisis. Integer tellus nulla, aliquam fringilla fringilla nec, aliquam non massa. Etiam scelerisque ex pellentesque, accumsan libero vel, congue arcu. Curabitur id viverra quam. Donec ut elit sapien.
                    </p>
                    <p>
                    Sed mollis sollicitudin porttitor. Vivamus placerat porta elementum. Nulla et felis nisi. Curabitur id interdum sem, vitae rhoncus nisl. Integer libero diam, sodales non mattis quis, rutrum a lorem. Nunc laoreet ipsum id enim maximus pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis in facilisis diam, eu interdum ligula. Donec mi mi, tincidunt sit amet dictum tempor, commodo quis ipsum.
                    </p>
                    <p>
                    Duis lobortis nisl vel fringilla vehicula. Praesent enim dui, cursus non tellus ut, cursus porttitor purus. Mauris interdum tellus ut orci facilisis, in accumsan dolor commodo. Phasellus at vehicula purus. Pellentesque pellentesque purus auctor, euismod risus eget, pulvinar ante. Morbi gravida lobortis nulla eget molestie. Mauris aliquet porta finibus. Aenean aliquet arcu eu est semper commodo.
                    </p>
            </div>
            <div class="col-12 col-lg-4 col-xl-3">

                <div class="row section-row">
                    <div class="col-lg-12 col-xl-12 col-12">
                        <div class="section-title text-left">Latest posts</div>
                    </div>
                </div>
                <div class="post-item -no-thumb">
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Hit the Appalachian Trail as it welcomes back long-distance trekkers</a></h1>
                    </div>
                </div>
                <div class="post-item -no-thumb">
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">This incredible oceanfront geothermal lagoon has opened in Iceland</a></h1>
                    </div>
                </div>
                <div class="post-item -no-thumb">
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">US tourists in New York City can get a one-shot vaccine</a></h1>
                    </div>
                </div>
                <div class="post-item -no-thumb">
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Greece opens beaches as international visitors return</a></h1>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="row section-row">
            <div class="col-lg-6 col-xl-6 col-8">
                <div class="section-title text-left">Related posts</div>
            </div>
            <div class="col-lg-6 col-xl-6 col-4 d-flex justify-content-end align-items-center">
                <div class="section-more text-right"><a href=""><span>Browse all</span> <i
                            class="bi bi-arrow-right-square-fill"></i></a></div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3 d-flex align-items-stretch">
                <div class="post-item -grid">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <a href="#">
                            <h1>Yourtitle Lorem ipsum
                        </a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 d-flex align-items-stretch">
                <div class="post-item -grid">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 d-flex align-items-stretch">
                <div class="post-item -grid">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="#">Jhon doe</a></span>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 d-flex align-items-stretch">
                <div class="post-item -grid">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <span class="meta-date">12 May 2021</span>
                        <span class="meta-author"><a href="">Jhon doe</a></span>

                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="container">

        <div class="row section-row">
            <div class="col-lg-6 col-xl-6 col-8">
                <div class="section-title text-left">Trending posts</div>
            </div>
            <div class="col-lg-6 col-xl-6 col-4  d-flex justify-content-end align-items-center">
                <div class="section-more text-right"><a href=""><span>Browse all</span> <i
                            class="bi bi-arrow-right-square-fill"></i></a></div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3  d-flex align-items-stretch">
                <div class="post-item -grid -cover">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <a href="#">
                            <h1>Yourtitle Lorem ipsum dolor sit amet consectetur.
                        </a></h1>
                        <a href="" class="post-item_more">Read more</a>

                    </div>
                </div>
            </div>
            <div class="col-lg-3  d-flex align-items-stretch">
                <div class="post-item -grid -cover">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <a href="" class="post-item_more">Read more</a>

                    </div>
                </div>
            </div>
            <div class="col-lg-3  d-flex align-items-stretch">
                <div class="post-item -grid -cover">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="#">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <a href="" class="post-item_more">Read more</a>

                    </div>
                </div>
            </div>
            <div class="col-lg-3  d-flex align-items-stretch">
                <div class="post-item -grid -cover">
                    <div class="post-item_thumb">
                        <a href="#"><img src="https://via.placeholder.com/400x300/f8f8f8/dddddd/"></a>
                    </div>
                    <div class="post-item_text">
                        <span class="meta-category"><a href="#">Travel news</a></span>
                        <h1><a href="">Yourtitle Lorem ipsum dolor sit amet consectetur.</a></h1>
                        <a href="" class="post-item_more">Read more</a>

                    </div>
                </div>
            </div>
        </div>
        <?php

        /*
                if ( have_posts() ) :

                    if ( is_home() && ! is_front_page() ) : ?>
        <header>
            <h1 class="page-title screen-reader-text"><?php single_post_title(); ?></a></h1>
        </header>

        <?php
                    endif;

                    while ( have_posts() ) : the_post();


                        //get_template_part( 'templates/parts/content', get_post_format() );

                    endwhile;

                    the_posts_navigation();

                else :

                    get_template_part( 'templates/_parts/content', 'none' );

                endif; */ ?>
    </div>

    <div class="page-section-fullwidth">
        <div class="page-section-fullwidth_image">
            <img src="https://via.placeholder.com/1600x600/f8f8f8/dddddd/">
        </div>
        <div class="page-section-fullwidth_content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-xl-12">
                        Hello world
                    </div>
                </div>
            </div>
        </div>
    </div>



</main><!-- #primary -->
<?php
get_footer();
?>
